name:                quotes-api
version:             0.1.0.0
github:              "githubuser/quotes-api"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/quotes-api#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - scotty
  - text
  - aeson
  - time
  - warp
  - wai
  - http-types
  - postgresql-simple
  default-extensions: OverloadedStrings
                      NamedFieldPuns
                      ScopedTypeVariables
                      DeriveGeneric

executables:
  quotes-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quotes-api

tests:
  quotes-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quotes-api
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
    - aeson-qq
    - text
    - utf8-string
    default-extensions: OverloadedStrings
                        NamedFieldPuns
                        ScopedTypeVariables
                        DeriveGeneric
